services:
  element-call:
    image: ghcr.io/element-hq/element-call:latest
    container_name: element-call
    restart: unless-stopped
    environment:
      - TZ=${TZ}
    networks:
      - backend
