services:
  element-web:
    image: ghcr.io/element-hq/element-web:latest
    container_name: element-web
    restart: unless-stopped
    volumes:
      - ./element/config.json:/app/config.json:ro
    networks:
      - backend
